### ISSUE TITLE
 This package does not build with GHC 9.4.8.

### ISSUE THREAD

**Issue by kindaro** [pxqr/intset#5]
## what I do

```
% git remote -v
origin	https://github.com/pxqr/intset.git (fetch)
origin	https://github.com/pxqr/intset.git (push)
% git rev-parse @
f4591d4e7074ce342949b7762f7ae666c63950ff
% ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.4.8
% cabal build
Build profile: -w ghc-9.4.8 -O1
In order, the following will be built (use -v for more details):
 - intset-0.1.1.0 (lib) (file src/Data/IntervalSet/Internal.hs changed)
Preprocessing library for intset-0.1.1.0..
Building library for intset-0.1.1.0..
[1 of 3] Compiling Data.IntervalSet.Internal ( src/Data/IntervalSet/Internal.hs, /tmp/intset/dist-newstyle/build/x86_64-linux/ghc-9.4.8/intset-0.1.1.0/build/Data/IntervalSet/Internal.o, /tmp/intset/dist-newstyle/build/x86_64-linux/ghc-9.4.8/intset-0.1.1.0/build/Data/IntervalSet/Internal.dyn_o ) [Source file changed]

src/Data/IntervalSet/Internal.hs:594:8: error:
    Suffix occurrence of @. For an as-pattern, remove the leading whitespace.
    |
594 | union t@ Bin {}       (Tip p bm) = insertBM  p bm t
    |        ^
Error: cabal: Failed to build intset-0.1.1.0.
```

## what should happen

Running `cabal build` should build the package.

## discussion

A few touches are needed.

* Remove white space about the `@` symbol in patterns, like in https://github.com/pxqr/base32-bytestring/issues/6.
* Replace `BS.inlinePerformIO` with `unsafePerformIO`.
* Add an instance of `Semigroup` to every instance of `Monoid`.
* Derive `Generic` on `IntSet`.

Here is a patch: <https://gist.github.com/kindaro/7f39d9be7cb9dfed77fd1301ba773f62>
